### ISSUE TITLE
How to use? Where examples?

### ISSUE THREAD

**Issue by remotehelp** [metaregistrar/php-dnssec-validator#1]
How to use it this? Where examples? :)

**Comment by metaregistrar** [comment]
Hi there,

I have added some explanation and a short test file

To use the repo, just clone it and use test.php for your first test.

**Comment by remotehelp** [comment]
Hello metaregistrar

What does this php-dnssec-validator? Where explanation in readme.md?

I find PHP DNSSEC solution for tested DNS resolver installed on client PC. For example: client installs on own pc unbound aka DNSSEC resolver end then him need pass the test.

some like this: http://dnssectest.sidnlabs.nl/test.php

**Comment by metaregistrar** [comment]
Hi there,

The php-dnssec-validator does roughly the same as dnssectest.sidnlabs.nl,
but it works much faster, because the test is more basic. Only the simplest
tests are executed, so see if a domain name is secured and if the DS
records match the records in the nameservers that are indicated.

We use this tool to swiftly test a lot of domain names (500.000 in about 60
minutes). For the ones that give an error we can use the SIDN tool to see
what the error is exactly and fix it.

To use the tool, simply clone it from Github and run test.php with a domain
name.

Vriendelijke groeten/kind regards,

Ewout de Graaf
Metaregistrar

2015-10-30 23:06 GMT+01:00 remoteshaman.com notifications@github.com:
